### ISSUE TITLE
Referral code shouldn't be change

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wp-loyalty-migration#28]
Here, I migrated the same user  at that time, a new referral code was generated
Step 1: Migrate the Woocommerce Point and Rewards Migration user 
so this scenario already referral code generated.
Step 2: Migrate the WPSwings points and rewards(include the existing customer)
Here, again migrate the same user so the new referral code is generated
![image](https://github.com/wployalty/wployalty_migration/assets/107607148/04669d15-9e7b-4c65-b813-504ae53ade12)
![image](https://github.com/wployalty/wployalty_migration/assets/107607148/e818a148-dfad-4c4a-85ff-8f17be8aee69)
![image](https://github.com/wployalty/wployalty_migration/assets/107607148/13e519ec-8c89-4ccc-bd81-791c21f07be6)

**Comment by sankeernaduraii** [comment]
issue fixed

![r1](https://github.com/user-attachments/assets/d2885419-4700-4493-b45d-1d7f01e11582)
![r2](https://github.com/user-attachments/assets/9e0431b2-357d-4886-ae5f-9a3a337ca9b7)
![r3](https://github.com/user-attachments/assets/ac41e61b-69f2-40ee-837b-82574348b10f)
![r4](https://github.com/user-attachments/assets/5a0a4118-628f-41ac-a706-7fe29ed796f0)
