### ISSUE TITLE
Files->Need to change the label for exported file name

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wp-loyalty-migration#47]
![image](https://github.com/user-attachments/assets/e4ae741e-fb19-496d-9495-c8ea2f35d796)

**Comment by srikumar03** [comment]
Fixed

**Comment by sankeernaduraii** [comment]
issue fixed


![screenshot-test2_local-2024_12_24-15_05_32](https://github.com/user-attachments/assets/ac3b036c-ea73-48da-bc68-022cd9ce8f56)

 
WPSwings points and rewards-exported file name changed

![screenshot-test1_local-2024_12_24-15_04_13](https://github.com/user-attachments/assets/41157e5c-dca2-464b-a605-5ec3496b882e)

Woocommerce points and rewards-exported file name changed


![screenshot-test2_local-2024_12_24-15_07_20](https://github.com/user-attachments/assets/cb219c6e-fe35-4da9-a102-b5cdf67d476a)

WooCommerce Loyalty Points and Rewards-exported file name changed
