### ISSUE TITLE
HTTP API calls error showing

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wp-loyalty-migration#50]
![image](https://github.com/user-attachments/assets/6535596a-d811-4743-a3f0-9e76e60c65b6)
![image](https://github.com/user-attachments/assets/4d4c2985-96e1-4ca9-a929-22a84a7e70ca)

**Comment by sabhari-krr** [comment]
Fixed

![image](https://github.com/user-attachments/assets/ddd3a23d-b39f-468c-a53f-7e253e380179)

**Comment by Mercypaul27** [comment]
Fixed
