### ISSUE TITLE
MIGRATION CANNOT BE ACCESSED IN FREE WPLOYALTY

### ISSUE THREAD

**Issue by sankeernaduraii** [wployalty/wp-loyalty-migration#56]
In WPloyalty free version migration is not accessible

![screenshot-test1_local-2024_12_23-13_07_11](https://github.com/user-attachments/assets/22ed9fb8-ac5e-4edb-8c59-fdc613f0b48c)
![Screenshot from 2024-12-23 13-03-59](https://github.com/user-attachments/assets/790f3644-9046-4638-80e0-7cb4deb5f3ef)

**Comment by srikumar03** [comment]
Fixed

**Comment by sankeernaduraii** [comment]
Issue fixed,migration is accessible in wployalty free version

![screenshot-test1_local-2024_12_24-15_01_11](https://github.com/user-attachments/assets/37242915-045e-4e16-aa4b-7af902dced86)
![screenshot-test1_local-2024_12_24-15_01_46](https://github.com/user-attachments/assets/2e820620-c8f4-478c-9cce-2c8d57bdd7ac)
![screenshot-test1_local-2024_12_24-15_02_14](https://github.com/user-attachments/assets/0c9d0114-0ae6-443a-8216-f10499a49c30)
