### ISSUE TITLE
Issue in export 

### ISSUE THREAD

**Issue by sankeernaduraii** [wployalty/wp-loyalty-migration#57]
1) In Export,if no users are there to export it shouldn't be displayed as undefined.It must displayed as "NO USERS TO EXPORT"
2) There is no button to exit the pop-up 

![screenshot-test2_local-2024_12_23-17_45_11](https://github.com/user-attachments/assets/e6add904-ca50-471a-87ea-8c3d056d776b)

**Comment by srikumar03** [comment]
Fixed!

**Comment by sankeernaduraii** [comment]
when the processed item count changes from 0 to 1 ,the export will be displayed else export button will not be displayed.issue fixed

![screenshot-test2_local-2024_12_24-15_42_27](https://github.com/user-attachments/assets/9d68846a-18a5-4183-932d-86298680d05b)

![screenshot-test2_local-2024_12_24-15_57_06](https://github.com/user-attachments/assets/2015c9d4-8c3e-4ff7-a939-f729bbb8b913)
