### ISSUE TITLE
WP Swings Migration-Processed itemsis shown wrong

### ISSUE THREAD

**Issue by sankeernaduraii** [wployalty/wp-loyalty-migration#58]
Totally 5 users were banned in wployalty expect them the total count should be 2996 but it shown wrong as 2896

![screenshot-test1_local-2024_12_26-10_34_33](https://github.com/user-attachments/assets/3206c5fc-4670-4fb9-8814-9088037039d6)

**Comment by sabhari-krr** [comment]
Fixed.

**Comment by sankeernaduraii** [comment]
Issue Fixed.

![screenshot-test1_local-2024_12_26-15_38_27](https://github.com/user-attachments/assets/0f8911e0-e578-4b62-ad1d-db9539cc8cc8)
