### ISSUE TITLE
Script validation

### ISSUE THREAD

**Issue by sankeernaduraii** [wployalty/wp-loyalty-migration#59]
when the user search for script in search bar,it should result in basic validation failed

![screenshot-test1_local-2024_12_26-15_49_33](https://github.com/user-attachments/assets/2935ac51-f941-4d6d-b411-d33d204a4696)

**Comment by srikumar03** [comment]
![Uploading image.png…]()

Fixed!

**Comment by sankeernaduraii** [comment]
when user enter script in search bar it results in basic validation failed ,Issue fixed.


[Screencast from 2024-12-27 09-04-15.webm](https://github.com/user-attachments/assets/193e250f-1c8e-429b-b07c-5e9a40333558)
