### ISSUE TITLE
issue in migrating the users in free version

### ISSUE THREAD

**Issue by sankeernaduraii** [wployalty/wp-loyalty-migration#60]
Migration job cannot be created in free version

[Screencast from 2024-12-27 10-02-13.webm](https://github.com/user-attachments/assets/08287d3c-b6db-4769-92a7-fedbb6b6211d)

**Comment by srikumar03** [comment]
Fixed!

**Comment by sankeernaduraii** [comment]
issue fixed 

![screenshot-final-test_local-2024_12_29-19_38_11](https://github.com/user-attachments/assets/c19e81ad-958e-4254-b5bc-021498aff5bd)

[Screencast from 2024-12-29 19-37-11.webm](https://github.com/user-attachments/assets/7ac5d4a3-8920-4b4b-be19-9f4826a9be93)
